repos:
- repo: local
  hooks:
  - id: black
    name: black
    stages: [commit]
    language: system
    entry: pipenv run black
    types: [python]

  - id: pycodestyle
    name: pycodestyle
    stages: [commit]
    language: system
    entry: pipenv run pycodestyle
    types: [python]